### PR TITLE
Analyzer

### PR DESCRIPTION
**Pull request by Abdullah104**

### CODE REVIEW

**Comment by pr-Mais** [comment]
Hey @Abdullah104 , thanks for the contribution!
Could you please fix the conflicts?

**Comment by Abdullah104** [comment]
I will work on it as soon as possible

**Comment by Abdullah104** [comment]
I fixed the conflicts. However, I just wanted to note that two of the files that had the conflict were committed with compilation time errors. Specifically, the SharedPreferencesService didn't have the type-defined value getters and setters, but I didn't change them because I didn't know if I should. If you want me to fix it. I will do it.

**Comment by pr-Mais** [comment]
Would you fix it please

**Comment by Abdullah104** [comment]
Yes sure

**Comment by Abdullah104** [comment]
This may seem weird, but I just opened the app to fix the error, and the error just wasn't there anymore. I think it may have been a problem with my editor. So sorry for the unnecessary delay.

**Comment by pr-Mais** [comment]
Thanks!

**Pull request merged**
